<?php require('template/header.phtml');?>

<div class="container">
    <div class="row">
        <div class="col-sm-12 p-4">
            <div class="card border-0" style="width: 70px">
                <img class="card-img-top" src="images/email.png" alt="email icon">
                EMail
            </div>
        </div>
        <div class="col-sm-12 p-4">
            <div class="card border-0" style="width: 70px">
                <img class="card-img-top" src="images/web.png" alt="web icon">
                Web
            </div>
        </div>
        <div class="col-sm-12 p-4">
            <div class="card border-0" style="width: 70px">
                <img class="card-img-top" src="images/files.png" alt="files icon">
                Files
            </div>
        </div>
    </div>
</div>

<?php require('template/footer.phtml') ?>
