<a name="card-link" href="/email.php?selected=<?php echo $email->getID() ?>&scrollpos=0" class="text-reset">
    <div class="card mt-1 mx-0">
        <?php if ($email->getUserAnswer() == 'real') : ?>
            <div class='card-header text-truncate bg-success'>
        <?php elseif ($email->getUserAnswer() == 'phishing') : ?>
            <div class='card-header text-truncate bg-danger'>
        <?php else : ?>
            <div class='card-header text-truncate'>
        <?php endif; ?>
            <p class="my-0"><?php echo substr($email->getFromName(), 0, 100) ?></p>
        </div>
        <?php if (isset($view->selectedEmail) && $view->selectedEmail->getID() == $email->getID()) : ?>
        <div class='card-body py-0 bg-info'>
        <?php else : ?>
        <div class='card-body py-0'>
        <?php endif ?>
            <p class="text-truncate my-0"><?php echo substr(filter_var($email->getSubject(), FILTER_SANITIZE_FULL_SPECIAL_CHARS), 0, 100) ?></p>
            <p class="text-truncate my-0"><?php echo substr(strip_tags ($email->getBody()), 0, 100) ?></p>
        </div>
    </div>
</a>