<?php require('template/header.phtml');?>

</div>

<div class="container bg-light border shadow mt-4" id="email-client">
    <div class="row">
        <div class="col-4 bg-dark py-1">
            <!--
            <form class="form-inline ml-md-0 ml-lg-5" action="../lotsearch" method="get">
                <div class="input-group">
                    <input type="text" class="form-control" name="search" placeholder="Search..." aria-label="Search" aria-describedby="search1">
                    <div class="input-group-append">
                        <button type="submit" class="img-thumbnail btn-outline-secondary input-group-text">
                            <img src="../images/bootstrap-icons/search.svg" alt="" width="16" height="16" title="Search">
                        </button>
                    </div>
                </div>
            </form>
            -->
        </div>
        <div class="col-2 bg-dark py-1">
            <span class="text-light">EMails Checked: <span id="answer-count">0</span>/<span id="email-count">0</span></span>
        </div>
        <div class="col-4 bg-dark py-1">
            <form action="/email.php" method="post">
                <button type="submit" class="btn btn-secondary" name="submit" value="true" id="answer-submit" disabled="true" data-bs-toggle="tooltip"
                        title="<h4>Step 4</h3><p>Once you have provided an answer to all of the emails, press Submit Answers to see how you did.</p><button class='btn btn-info' type='button' id='guide-4-next'>Let's go!</button>">Submit Answers</button>
            </form>
        </div>
        <div class="col-2 bg-dark py-1">
            <button class="btn btn-secondary float-right" type="submit" name="reset" value="true" id="answer-reset">Reset Answers</button>
        </div>
    </div>
    <div class="row">
        <div class="col col-sm-4 p-0" id="email-list">
            <?php
                $index = 0;
                foreach ($view->emails as $email) {
                    include 'Views/email_card.phtml';
                    $index++;
                }
            ?>
        </div>
        <div class="col col-sm-8">
            <div class="row">
                <div class="col col-12 bg-white" id="email-content" data-bs-toggle="tooltip"
                     title="<h4>Step 2</h3><p>Hover over words, images and links in the email to get hints that will guide you through identifying phishing emails.</p><button class='btn btn-info' type='button' id='guide-2-next'>Next</button>">
                    <div class="pb-3" id="email-header">
                        <h5>From:
                            <span id="selected-from-name"></span>
                            &lt;<span id="selected-from"></span>&gt;
                        </h5>
                        <h5>Subject: <span id="selected-subject"></span></h5>
                    </div>
                    <div id="email-body"><p class="text-center">Select an email to start</p></div>
                </div>
                <div class="col col-12">
                    <div class="container">
                        <div class="row">
                            <div class="col-6">
                                <div clas="row" data-bs-toggle="tooltip">
                                    <form class="form-inline" id="answer-form" style="display: none" guide-step="3"
                                          title="<h4>Step 3</h3><p>After reviewing the email, make a decision, is it a real eamil or is it phishing for information?.</p><button class='btn btn-info' type='button' id='guide-3-next'>Next</button>">
                                        <div class="col col-6">
                                            <input type="radio" class="btn-check form-control" name="answer" value="real" id="radio-real" autocomplete="off" checked>
                                            <label class="btn btn-outline-success btn-lg" for="radio-real" id="radio-real-label">Real</label>
                                        </div>
                                        <div class="col-6">
                                            <input type="radio" class="btn-check form-control" name="answer" value="phishing" id="radio-phishing" autocomplete="off">
                                            <label class="btn btn-outline-danger btn-lg" for="radio-phishing" id="radio-phishing-label">Phishing</label>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12" id="status">&nbsp;</div>
    </div>
</div>

<?php require('template/footer.phtml') ?>
