<?php require('template/header.phtml');?>

</div>

<div class="container bg-light border shadow mt-4">
    <div class="row">
        <div class="col-4 bg-dark">
            <form class="form-inline ml-md-0 ml-lg-5" action="../lotsearch" method="get">
                <div class="input-group">
                    <input type="text" class="form-control" name="search" placeholder="Search..." aria-label="Search" aria-describedby="search1">
                    <div class="input-group-append">
                        <button type="submit" class="img-thumbnail btn-outline-secondary input-group-text">
                            <img src="../images/bootstrap-icons/search.svg" alt="" width="16" height="16" title="Search">
                        </button>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-2 bg-dark">
            <span class="text-light">EMails Checked: <?php echo $view->answerCount . '/' . $view->emailCount ?></span>
        </div>
        <div class="col-4 bg-dark">
            <form action="/email.php" method="post">
                <?php if ($view->answerCount == $view->emailCount && $view->emailCount > 0) : ?>
                <button type="submit" class="btn btn-secondary" name="submit" value="true">Submit Answers</button>
                <?php else : ?>
                <button class="btn btn-secondary" disabled>Submit Answers</button>
                <?php endif ?>
            </form>
        </div>
        <div class="col-2 bg-dark">
            <form class="" action="/email.php" method="post">
                <button class="btn btn-secondary float-right" type="submit" name="reset" value="true">Reset Answers</button>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col col-sm-4" id="email-list">
            <?php
                foreach ($view->emails as $email) {
                    include 'Views/email_card.phtml';
                }
            ?>
        </div>
        <div class="col col-sm-8">
            <div class="row">
                <div class="col col-12 bg-white" id="email-content">
                    <?php
                    if (isset($view->selectedEmail)) {
                        include 'email_header.phtml';
                        echo $view->transformedBody;
                    } else {
                        echo "<p class='text-center'>Select an email to start</p>";
                    }
                    ?>
                </div>
                <div class="col col-12">
                    <div class="container">
                        <div class="row">
                            <div class="col-12">
                                <?php if (isset($view->selectedEmail)) : ?>
                                    <form class="form-inline" action="/email.php" method="post">
                                        <input type="hidden" name="selected" value="<?php echo $view->selectedEmail->getId() ?>">

                                        <?php if ($view->selectedEmail->getUserAnswer() == 'real') : ?>
                                            <button type="submit" name="answer" value="real" class="btn btn-success btn-lg m-auto" type="button">Real</button>
                                            <button type="submit" name="answer" value="phishing" class="btn btn-outline-danger btn-lg m-auto" type="button">Phishing</button>
                                        <?php elseif ($view->selectedEmail->getUserAnswer() == 'phishing') : ?>
                                            <button type="submit" name="answer" value="real" class="btn btn-outline-success btn-lg m-auto" type="button">Real</button>
                                            <button type="submit" name="answer" value="phishing" class="btn btn-danger btn-lg m-auto" type="button">Phishing</button>
                                        <?php else : ?>
                                            <button type="submit" name="answer" value="real" class="btn btn-outline-success btn-lg m-auto" type="button">Real</button>
                                            <button type="submit" name="answer" value="phishing" class="btn btn-outline-danger btn-lg m-auto" type="button">Phishing</button>
                                        <?php endif; ?>


                                    </form>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12" id="status">&nbsp;</div>
    </div>
</div>

<?php require('template/footer.phtml') ?>

<script type="application/javascript">
var tooltipTriggerList = [].slice.call(document.querySelectorAll('[hint]'))

var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
    return new bootstrap.Tooltip(tooltipTriggerEl, {html: true, toggle: 'tooltip', placement: 'auto'})
})

function setStatus(tag) {
    var statusValue = document.getElementById("status");
    statusValue.innerText = tag.attributes.getNamedItem("url").value;
}

function clearStatus(tag) {
    var statusValue = document.getElementById("status");
    statusValue.innerHTML = "&nbsp;";
}
</script>
