<?php require('template/header.phtml') ?>

<form name="index" action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">

    <div class="col-12 padding">
        <h1 class="display-4 text-center">WELCOME !</h1>
    </div>
    <hr>
    <div class="container-fluid padding">
        <div class="row padding">
            <div class="col-lg-6">
                <h2>SECTION 1</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna
                    aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                    Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint
                    occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                <br>
            </div>
            <div class="col-lg-6">
                <figure>
                    <img src="images/section1.jpg" alt="IMAGE 1" class="img-fluid">
                </figure>
            </div>
        </div>
    </div>
    <hr class="my-4">
    <div class="container-fluid padding">
        <div class="row padding">
            <div class="col-lg-6">
                <figure>
                    <img src="images/section2.jpg" alt="IMAGE 2" class="img-fluid">
                </figure>
            </div>
            <div class="col-lg-6">
                <h2>SECTION 2</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna
                    aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                    Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur
                    sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            </div>
        </div>
    </div>
    <hr class="my-4">
    <div class="container-fluid padding">
        <div class="row padding">
            <div class="col-lg-6">
                <h2>SECTION 3</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna
                    aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                    Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur
                    sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                <br>
            </div>
            <div class="col-lg-6">
                <figure>
                    <img src="images/section3.jpg" alt="IMAGE 3" class="img-fluid">
                </figure>
            </div>
        </div>
    </div>
</form>
<?php require('template/footer.phtml') ?>
