<?php require('template/header.phtml') ?>

    <form name="lots" action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
        <h3> Personal Details: </h3>
        <table class="table table-hover">
            <thead>
            <tr>
                <th>E Mail</th><th>First Name</th><th>Last Name</th><th>Image</th><th>Address ID</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($view->userData as $user) {
                echo '<tr> <td>' . $user->getEmail() . '</td> <td>' . $user->getFirstName() . '</td> <td>' . $user->getLastName() . '</td> <td>' . '<img src="images/blank-profile-picture.png" alt="no picture" />' . '</td> <td>' . $user->getUserAddress() . '</td> </tr>';
            }
            ?>
            </tbody>
        </table>

    </form>

<?php require('template/footer.phtml') ?>