<?php require('template/header.phtml') ?>

    <form name="profile" action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">

        <h3> Personal Details: </h3>
        <table class="table table-hover">
            <thead>
            <tr>
                <th>E Mail</th><th>First Name</th><th>Last Name</th><th>Image</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($view->userData as $user) {
                echo '<tr> <td>' . $user->getEmail() . '</td> <td>' . $user->getFirstName() . '</td> <td>' . $user->getLastName() . '</td> <td>' . '<img src="images/blank-profile-picture.png" alt="no picture" />' . '</td> <td> </tr>';
            }
            ?>
            </tbody>
        </table>

        <h3> Test results: </h3>
        <table class="table table-hover">
            <thead>
            <tr>
                <th>Test ID</th><th>Test type</th><th>Result</th><th>Date</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($view->testData as $test) {
                echo '<tr> <td>' . $test->getTestID() . '</td> <td>' . $test->getTestName() . '</td> <td>' . $test->getResult() . '</td> <td>' . $test->getDate() . '</td> </tr>';
            }
            ?>
            </tbody>
        </table>

    </form>

<?php require('template/footer.phtml') ?>