<?php require('template/header.phtml'); ?>


    <div class="register">
        <h1>Register</h1>
        <form action="register.php" method="post">

            <label for="email">
                <i class="fas fa-user"></i>
            </label>
            <input type="text" name="email" placeholder="Email" required>

            <label for="firstname">
                <i class="fas fa-user"></i>    <!-- Download Icon ! -->
            </label>
            <input type="text" name="firstname" placeholder="First Name" required>

            <label for="lastname">
                <i class="fas fa-user"></i>    <!-- Download Icon ! -->
            </label>
            <input type="text" name="lastname" placeholder="Last Name" required>

            <label for="password">
                <i class="fas fa-lock"></i>    <!-- Download Icon ! -->
            </label>
            <input type="password" name="password" placeholder="Password" required>

            <label for="confirmpassword">
                <i class="fas fa-lock"></i>     <!-- Download Icon ! -->
            </label>
            <input type="password" name="confirmPassword" placeholder="Confirm Password" required>

            <input type="submit" value="Register">

            <p class="option">Already registered? <a href="login.php">Login</a></p>
        </form>
    </div>

<?php require('template/footer.phtml') ?>