<?php require('template/header.phtml'); ?>


    <div class="webbrowser">
        <div class="row">
            <div class="col-xs-12">

                <div class="container">
                    <ul class="nav justify-content-center">
                        <li class="nav-item">
                            <a class="nav-link" href="#" onclick="changeImg('images/web-info.png')">Info</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#" onclick="changeImg('images/web-linkedin.png')">http://www.Iinkdin.com/</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#" onclick="changeImg('images/web-paypal.png')">https://www.paypal.com/</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#" onclick="changeImg('images/web-deal.png')">https://www.currys.co.uk/mac</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#" onclick="changeImg('images/web-checkout.png')">https://www.currys.co.uk/checkout</a>
                        </li>
                    </ul>
                </div>

                <div class="container">
                    <div class="col-md-12 px-0">
                        <img id="change_img_target" class="img-fluid" src="images/web-linkedin.png">
                    </div>
                </div>

            </div>
        </div>
    </div>


    <hr class="my-4">

    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">

                <form action="webbrowser.php" method="post">

                    <h3>Please answer which of the above pages raising the following concerns: </h3>

                    <div class="col-md-6>">
                        <h6>Unreliable Address Bar</h6>
                    </div>
                    <div class="col-md-6>">
                        <input list="browsers" name="browser1" required>
                        <datalist id="browsers">
                            <option value="LinkedIn">
                            </option><option value="PayPal">
                            </option><option value="Currys.co.uk/Mac">
                            </option><option value="Currys.co.uk/checkout">
                            </option></datalist>
                    </div>

                    <div class="col-md-6>">
                        <h6>Unreliable Content</h6>
                    </div>
                    <div class="col-md-6>">
                        <input list="browsers" name="browser2" required>
                        <datalist id="browsers">
                            <option value="LinkedIn">
                            </option><option value="PayPal">
                            </option><option value="Currys.co.uk/Mac">
                            </option><option value="Currys.co.uk/checkout">
                            </option></datalist>
                    </div>

                    <div class="col-md-4>">
                        <h6>Suspicious Deal</h6>
                    </div>
                    <div class="col-md-4>">
                        <input list="browsers" name="browser3" required>
                        <datalist id="browsers">
                            <option value="LinkedIn">
                            </option><option value="PayPal">
                            </option><option value="Currys.co.uk/Mac">
                            </option><option value="Currys.co.uk/checkout">
                            </option></datalist>
                    </div>

                    <div class="col-md-4>">
                        <h6>Alarming Payment Method</h6>
                    </div>
                    <div class="col-md-4>">
                        <input list="browsers" name="browser4" required>
                        <datalist id="browsers">
                            <option value="LinkedIn">
                            </option><option value="PayPal">
                            </option><option value="Currys.co.uk/Mac">
                            </option><option value="Currys.co.uk/checkout">
                            </option></datalist>
                    </div>

                    <input type="submit">
                </form>
            </div>
        </div>
    </div>

    <script>
        function changeImg(url) {
            document.getElementById("change_img_target").src = url;
        }
    </script>

<?php require('template/footer.phtml') ?>