    </div>



<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src = "https://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
    <script src="js/bootstrap.bundle.min.js"></script>
    <?php
    if (isset($view->scripts)) {
        foreach ($view->scripts as $script) {
            echo "<script src=\"$script\"></script>";
        }
    }
    ?>
</body>
</html>