<?php require_once 'session_helper.php'; ?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">


    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.css" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="/css/bootstrap-theme.css" rel="stylesheet">
    <link href="/css/my-style.css" rel="stylesheet">
    <link href="/css/my-new-style.css" rel="stylesheet">

    <title>Auction House - <?php echo $view->pageTitle; ?></title>
</head>

<body role=""document">

<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="index.php">Auction House</a>
        </div>
        <ul class="nav navbar-nav">
            <li><a href="lotList.php">Lots</a></li>
            <li><a href="lotFullList.php">All Lots</a></li>
        </ul>
        <form class="navbar-form navbar-left" action="lotList.php" method="post">
            <div class="form-group">
                <input type="text" class="form-control" name="searchBox" placeholder="Search"/>
            </div>
            <button type="submit" class="btn btn-default" name="searchButton">Submit</button>
        </form>
        <ul class="nav navbar-nav navbar-right">
            <li>
                <?php if(isLoggedIn()) : ?>
                <a href="profile.php"><span class="glyphicon glyphicon-user"></span> My Account</a></li>
                <?php else : ?>
                <a href="register.php"><span class="glyphicon glyphicon-user"></span> Sign Up</a>
                <?php endif; ?>
            </li>
            <li>
                <?php if(isLoggedIn()) : ?>
                <a href="logout_index.php"><span class="glyphicon glyphicon-log-in"></span> Logout</a>
                <?php else : ?>
                <a href="login.php"><span class="glyphicon glyphicon-log-in"></span> Login</a>
                <?php endif; ?>
            </li>
        </ul>
    </div>
</nav>

<div class="container">
        <div  class="row">
            <div id="title" class="col-xs-12">
                <img src="images/auction-house-logo.png" alt="Auction House" />
                    <div class="pull-right"> <h1><?php echo $view->pageTitle ?> </h1></div>

            </div>
        </div>

    <div id="content" class="col-xs-16">



